Controllers films users
DmitriiDerendyaev/java-filmorate pull request #5
Opened 2023-10-02 20:01 UTC by DmitriiDerendyaev

Реализованы контроллеры для приложения Filmorate. Написана прослойка в виде сервисов и Мок тесты для изолированной проверки(просто решил попробовать, жду отзыв))

2023-10-03 08:24 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final HashMap<Integer, Film> films = new HashMap<>();
Лишние пару строк

2023-10-03 08:25 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmService filmService;
Отлично что выделил слой сервисов из контроллера

2023-10-03 08:32 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/handler/ErrorHandler.java
> +
В данном спринте нет требований к ErrorHandler (будет в следующем), но раз уж сделал, то хорошо бы добавить трансляцию кастомного исключения в респонс.

2023-10-03 08:32 UTC, DmitriiDerendyaev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final HashMap<Integer, Film> films = new HashMap<>();
Ааааа, вы про неиспользованные HashMap и currentId?

2023-10-03 08:35 UTC, VadimZharkov requested changes
Т.к. у обоих сервисов одинаковая функциональнось по работе с сущностями модели, то можно выделить ее в базовый сервис. Сущности модели тоже имеют общую часть - идентификатор, и можно сделать базовый класс, назвать например Entity.
В итоге базовый сервис мог бы иметь такое определение

```
public abstract class Service<T extends Entity> {
    поля и методы для сохранения, получения сущностей, мапа и генерация идентификатора
} 
```

2023-10-03 08:48 UTC, DmitriiDerendyaev commented on src/main/java/ru/yandex/practicum/filmorate/handler/ErrorHandler.java
> +
По типу, создаем кастомное исключение:
```
public class InvalidValidation extends RuntimeException{
    public InvalidValidation(String message) {
        super(message);
    }
}
```
Но как быть дальше? Я прочитал, что ErrorHandler отлавливает по нарушению валидации именно MethodArgumentNotValidException.

Если я заменю на кастомный, то как он поймет, что ловить?

Или как сделать так, чтобы при ошибке валидации было выброшено мое кастомное исключение?

2023-10-03 09:31 UTC, DmitriiDerendyaev commented
@VadimZharkov позвольте атаковать вас вопросами еще чуть-чуть

Сейчас диаграмма выглядит так:
![image](https://github.com/DmitriiDerendyaev/java-filmorate/assets/55666026/9b36cc00-4b77-46ce-a048-f802f9f302f6)

А сделать вы предлагаете так(Получается Entity тоже абстрактный?):
![image](https://github.com/DmitriiDerendyaev/java-filmorate/assets/55666026/4af22db3-76dc-410a-ad17-dc8d3f5e0552)

По поводу сервисов, сейчас они выглядят так:
![image](https://github.com/DmitriiDerendyaev/java-filmorate/assets/55666026/f5ff9581-0c02-461d-9c64-a610cbf5265a)

А нужно примерно так?:
![image](https://github.com/DmitriiDerendyaev/java-filmorate/assets/55666026/0e5b6d86-74c6-4c0d-b7a0-bba092260fe1)

2023-10-03 09:43 UTC, VadimZharkov commented
> Entity

да так и имел ввиду, можно сделать абстрактным (не особо принципиально)

2023-10-03 09:46 UTC, VadimZharkov commented
> А нужно примерно так?:

HashMap лучше поместить в базовый класс Service
и далее `public class UserService extends Service<User> {...}`

2023-10-04 06:06 UTC, VadimZharkov approved these changes

2023-10-05 21:30 UTC, merged